type User {
	id: ID!
	name: String!
	avatar: String!
	email: String!
}

type PageInfo {
	startCursor: Int
	hasNextPage: Boolean
}

type userResult {
	users: [User]
	pageInfo: PageInfo
}

type Query {
	users(first: Int, afterCursor: Int): userResult
}
